name: ntfy_client
description: Simple ntfy subscriber
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  eventsource: ^0.4.0

flutter:
  uses-material-design: true
